# Generated by Django 3.1.3 on 2021-07-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('spID', models.AutoField(primary_key=True, serialize=False)),
                ('imgSrc', models.CharField(max_length=512)),
                ('sName', models.CharField(max_length=30)),
                ('sPrice', models.CharField(max_length=30)),
                ('sDesc', models.CharField(max_length=512)),
                ('cName', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'o_card',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('sID', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=30)),
                ('icon', models.CharField(max_length=30)),
                ('href', models.CharField(max_length=30)),
                ('type', models.IntegerField()),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('modifyTime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'o_service',
            },
        ),
        migrations.CreateModel(
            name='tabpanel',
            fields=[
                ('ckID', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=30)),
                ('pos', models.CharField(max_length=30)),
                ('loc', models.IntegerField()),
            ],
            options={
                'db_table': 'o_tabpanel',
            },
        ),
    ]
