# Generated by Django 3.1.3 on 2021-07-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='href',
            field=models.CharField(max_length=512),
        ),
    ]
