# Generated by Django 3.1.3 on 2021-08-02 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onestep', '0002_auto_20210729_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cName',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='onestep.tabpanel'),
        ),
    ]
