# Generated by Django 3.1.3 on 2021-08-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestep', '0003_auto_20210802_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='imgSrc',
            field=models.ImageField(null=True, upload_to='menuimg', verbose_name='商品图片'),
        ),
    ]
