# Generated by Django 3.1.3 on 2021-08-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestep', '0004_auto_20210802_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabpanel',
            name='mSrc',
            field=models.ImageField(null=True, upload_to='menuimg', verbose_name='商铺图片'),
        ),
    ]
