# Generated by Django 3.1.3 on 2021-08-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestep', '0005_tabpanel_msrc'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('bSrc', models.ImageField(null=True, upload_to='banner', verbose_name='banner')),
            ],
        ),
        migrations.CreateModel(
            name='NewsLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=888)),
            ],
        ),
    ]
