# Generated by Django 3.1.3 on 2021-08-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestep', '0006_banner_newsline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsline',
            name='subtitle',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
