# Generated by Django 3.1.3 on 2021-08-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestep', '0007_auto_20210803_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsline',
            name='subtitle',
            field=models.CharField(max_length=255),
        ),
    ]
