# Generated by Django 3.1.3 on 2021-08-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestep', '0008_auto_20210803_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsline',
            name='href',
            field=models.CharField(max_length=888, null=True),
        ),
    ]
